# Forces new Travis-CI Infrastructure
sudo: false

language: php
php:
  - '5.6'
  - '7.0'
  - '7.2'

env:
  global:
    - RUN_PHPCS="yes"
    - INSTALL_MEMCACHE="yes"
    - INSTALL_MEMCACHED="yes"
    - INSTALL_REDIS="yes"

matrix:
  fast_finish: true

before_script:
  - phpenv config-rm xdebug.ini
  # Make sure all dev dependencies are installed
  - composer install

script:
  #- libraries/vendor/bin/phpunit --configuration travisci-phpunit.xml
  - sh -c "bin/phpcs --report=full --extensions=php -p --standard=build/phpcs/Joomla .;"
